### PR TITLE
fix(stella-records): move the published-record collision test to its own crate

### LINKED ISSUE #5901: main is red: compile fails on the merged tree
The post-merge canary tested `main` at `ffcda37fe` and it is red.

**This names the commit that was tested, not the commit that broke the tree.**
This run did not check `ffcda37fe`'s parent, so the break may be older —
possibly by many merges. Confirm before reverting anything: re-run the failing
check on `ffcda37fe^` and walk back while it still fails.

Failing: **compile**

### `compile`

```
    Checking stella-protocol v0.9.326 (/home/runner/work/stella/stella/crates/stella-protocol)
    Checking stella-home v0.9.326 (/home/runner/work/stella/stella/crates/stella-home)
    Checking stella-embed v0.9.326 (/home/runner/work/stella/stella/crates/stella-embed)
    Checking stella-diff v0.9.326 (/home/runner/work/stella/stella/crates/stella-diff)
    Checking stella-tty v0.9.326 (/home/runner/work/stella/stella/crates/stella-tty)
    Checking stella-diag v0.9.326 (/home/runner/work/stella/stella/crates/stella-diag)
    Checking stella-transcript v0.9.326 (/home/runner/work/stella/stella/crates/stella-transcript)
    Checking stella-tui-theme v0.9.326 (/home/runner/work/stella/stella/crates/stella-tui-theme)
    Checking stella-autonomy v0.9.326 (/home/runner/work/stella/stella/crates/stella-autonomy)
    Checking stella-context v0.9.326 (/home/runner/work/stella/stella/crates/stella-context)
   Compiling stella-cli v0.9.326 (/home/runner/work/stella/stella/crates/stella-cli)
    Checking stella-core v0.9.326 (/home/runner/work/stella/stella/crates/stella-core)
    Checking stella-store v0.9.326 (/home/runner/work/stella/stella/crates/stella-store)
    Checking stella-plugin v0.9.326 (/home/runner/work/stella/stella/crates/stella-plugin)
    Checking stella-graph v0.9.326 (/home/runner/work/stella/stella/crates/stella-graph)
    Checking stella-model v0.9.326 (/home/runner/work/stella/stella/crates/stella-model)
    Checking stella-records v0.9.326 (/home/runner/work/stella/stella/crates/stella-records)
    Checking stella-tools v0.9.326 (/home/runner/work/stella/stella/crates/stella-tools)
    Checking stella-mcp v0.9.326 (/home/runner/work/stella/stella/crates/stella-mcp)
    Checking stella-observatory v0.9.326 (/home/runner/work/stella/stella/crates/stella-observatory)
    Checking stella-engine v0.9.326 (/home/runner/work/stella/stella/crates/stella-engine)
    Checking stella-serve v0.9.326 (/home/runner/work/stella/stella/crates/stella-serve)
    Checking stella-tui v0.9.326 (/home/runner/work/stella/stella/crates/stella-tui)
    Checking stella-fleet v0.9.326 (/home/runner/work/stella/stella/crates/stella-fleet)
    Checking stella-runtime v0.9.326 (/home/runner/work/stella/stella/crates/stella-runtime)
    Checking loop-bench v0.1.0 (/home/runner/work/stella/stella/bench/loop-bench)
    Checking stella-parity v0.9.326 (/home/runner/work/stella/stella/crates/stella-parity)
error[E0433]: cannot find `ingest` in `stella_core`
  --> crates/stella-core/tests/published_records_do_not_collide.rs:18:18
   |
18 | use stella_core::ingest::record::EnforcementMode;
   |                  ^^^^^^ could not find `ingest` in `stella_core`

error[E0432]: unresolved import `stella_core::records`
  --> crates/stella-core/tests/published_records_do_not_collide.rs:19:18
   |
19 | use stella_core::records::{
   |                  ^^^^^^^ could not find `records` in `stella_core`

Some errors have detailed explanations: E0432, E0433.
For more information about an error, try `rustc --explain E0432`.
error: could not compile `stella-core` (test "published_records_do_not_collide") due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
```

### Why this was not caught before the merge

These checks are enforced against a shared cell — something every PR of a
given shape must write. Usually that is a file (`Cargo.lock`,
`scripts/file-size-baseline.txt`); it can equally be a *seam* two branches
each redesign in good faith (#3659). Either way, two branches can each be
correct, pass every check, and still compose into a broken tree once both
land. No pre-merge check has both halves in front of it, which is why this
canary exists (#3332).

### The two merges that composed

Established after the fact, and recorded here because the header above is right
that the tested commit is not necessarily the breaking one:

- **#5829** (merged 05:35, `913e21a0`) moved the record plane out of
  `stella-core` — `records`, `ingest` and `context_record` now live in
  `stella-records`.
- **#5855** (merged 06:09, `ffcda37f`) **added**
  `crates/stella-core/tests/published_records_do_not_collide.rs`, importing
  `stella_core::ingest::record::EnforcementMode` and `stella_core::records::{...}`.

`git cat-file -e` finds that path absent at both `913e21a0` and `913e21a0^`, so
the file did not exist before or at the extraction and was written against a
base where those imports still resolved. Neither branch is wrong alone.

### How to fix

```sh
git checkout main && git pull
```

...then, per failing check:

#### `compile`

```sh
cargo check --workspace --all-targets --locked
```

Land it on its own from a fresh `main` — do not fold it into an unrelated PR,
for the reason AGENTS.md gives about the file-size baseline.

### Definition of done

- [x] `compile` passes on a fresh `main` with the fix applied
- [x] The repair landed on its own from a fresh `main`, not folded into an
      unrelated PR.

Tick these on the repair PR's own tree — each is a command you can run before
you merge. The canary closes this issue itself on its next green run, so a box
nobody ticks costs the issue nothing; SCR-003's gate is what reads them, and it
runs on the PR.

### Blast radius while this is open

A red `main` reds every open PR, so the next contributor inherits a failure
they did not cause and may spend their session on it.

If **compile** is among the failures, nothing builds: the whole test suite and
the release binary are down, not one crate. If **lockfile-sync** is, everything
that passes `--locked` breaks — the MSRV check, the `stella-serve` container
build, and `install.sh`, which reaches people installing from source rather
than only CI.

### PR DESCRIPTION
**Pull request by macanderson**
## What and why

`main` does not compile. `cargo check --workspace --all-targets` fails on two unresolved imports:

```
error[E0433]: cannot find `ingest` in `stella_core`
  --> crates/stella-core/tests/published_records_do_not_collide.rs:18:18
error[E0432]: unresolved import `stella_core::records`
  --> crates/stella-core/tests/published_records_do_not_collide.rs:19:18
```

The record plane left `stella-core` in #5829 — `records`, `context_record` and `ingest` are `stella-records` modules now. #5855 added this integration test against the old paths at the same time. Both branches were green on their own; only the composition is wrong, which is the shape the post-merge canary exists to catch and did.

## The fix

The test moves to `crates/stella-records/tests/published_records_do_not_collide.rs` and imports `stella_records::ingest::record::EnforcementMode` and `stella_records::records::{…}`.

Moved rather than given a dev-dependency back into `stella-core`: everything it exercises — `load_context_file`, `assign_handles`, `detect_conflicts`, `is_suspended`, `EnforcementMode` — is `stella-records`'s own public surface, and pointing a core dev-dependency at the crate that already depends on core would put the edge back the way the extraction removed it.

Nothing else had to change. `stella-records` already declares the `toml` dev-dependency the test uses, and the crate sits at the same depth under `crates/`, so the `../../.stella/rules` the test reads resolves unchanged.

## Witness mechanism

The compiler. The test does not build on `main` and does build here; CI's `fmt + clippy + test` is the evidence, since the failing job is a workspace build.

`make guards-fast` is clean locally, `check-deleted-tests` sees a move rather than a deletion, and `git mv` staged it so the rename is visible to the guards that follow renames.

Tests deleted: None — `no_two_published_records_collide` and `every_published_hard_guard_arms` both move with the file and keep their names.

Closes #5901

## Summary by Sourcery

Restore workspace compilation by placing the published-record collision test alongside the record-plane APIs it exercises.

Bug Fixes:
- Move the published-record collision integration test to `stella-records` and update its imports so workspace builds no longer reference removed `stella-core` modules.

Tests:
- Preserve both published-record collision checks while relocating their test crate.

### CODE REVIEW

**Comment by macanderson** [comment]
Closing as a duplicate of #5906 — not because anything here is wrong, but because three sessions each claimed #5901 within four minutes and two of them opened a PR.

**The diffs are byte-identical.** Both rename `crates/stella-core/tests/published_records_do_not_collide.rs` to `crates/stella-records/tests/` and repoint the two imports at `stella_records::{ingest,records}`; `git diff` between the two heads is empty. The reasoning in both commit messages is the same and both are correct: `stella-records` depends on `stella-core`, so a dev-dependency back the other way would invert the edge rather than repair it.

#5906 is kept because it was opened first (06:25:58 vs 06:26:54) and its commit message names the rename for `check-deleted-tests` ("Tests deleted: none"), which that guard reads on the PR.

**The fix is verified**, so nothing is lost by closing this one. Running the moved test in its new crate:

```
$ cargo test -p stella-records --test published_records_do_not_collide
   Compiling stella-records v0.9.326
    Finished `test` profile [unoptimized + debuginfo] target(s) in 24.31s
     Running tests/published_records_do_not_collide.rs

running 2 tests
test no_two_published_records_collide ... ok
test every_published_hard_guard_arms ... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

Exit code 0. Both test functions survive the move, and `stella_records::ingest` / `stella_records::records` are public modules in that crate's `lib.rs`, so the imports resolve.

#5901 stays open and will be closed by #5906.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by macanderson** [comment]
Closing as a duplicate of #5906.

Three PRs are open against #5901 with byte-identical diffs — #5906 (06:25:58), this one (06:26:54), and #5908 (draft). All three rename `crates/stella-core/tests/published_records_do_not_collide.rs` into `crates/stella-records/tests/`, change the same two import lines, and carry the same pre-image blob (`5eb95c351..39932ff55`). Nothing distinguishes the resulting trees.

This is the collision AGENTS.md § "the canary" describes: every session with an open PR sees the red at once and reaches the same correct conclusion, which is why `scripts/main-red-claim.sh` is a step rather than a judgement (#4672–#4674 merged the same two-line fix 95 seconds apart).

Consolidating on #5906 because it was opened first and its checks are furthest along. That is the claim discipline the script encodes — first claim wins — and with ~33 open PRs the runner pool is saturated, so retiring two redundant 18-check runs gets `main` green sooner.

No judgement on this PR's content. Its description is the better of the three: it names #5829 and #5855 as the two branches that were each green alone and wrong composed, which is the most useful record of *why* `main` broke. Worth carrying into the merge commit or #5901 if anyone wants that reasoning preserved.

Reopen if #5906 fails for a reason that does not apply here — being identical, that should not happen.

---
_Generated by [Claude Code](https://claude.ai/code)_
