### ISSUE TITLE
main is red on three axes: stella-pipeline tests don't compile, clippy arity, and a private intra-doc link

### ISSUE THREAD

**Issue by macanderson** [macanderson/stella#1972]
## Problem

`origin/main` at `43402ae` fails **three** of the gate's steps. Every PR branched from it inherits a red `fmt + clippy + test` job that has nothing to do with its diff.

Reproduce from a clean checkout, nothing else applied:

```bash
git worktree add /tmp/mainchk origin/main --detach && cd /tmp/mainchk
cargo test -p stella-pipeline --no-run     # (1)
cargo clippy -p stella-pipeline            # (2)
RUSTDOCFLAGS="-D warnings" cargo doc -p stella-cli --no-deps   # (3)
```

### (1) The test suite does not compile — #1945 shipped a test referencing fixtures it never added

```
error[E0425]: cannot find value `PassingShell` in this scope
  --> crates/stella-pipeline/src/pipeline/tests/verification_hardening/flip_halt_arming.rs:42:21
error[E0425]: cannot find function `shell_call_result` in this scope
  --> crates/stella-pipeline/src/pipeline/tests/verification_hardening/flip_halt_arming.rs:31:9
```

Two use sites, zero definitions:

```console
$ git grep -E 'PassingShell|shell_call_result' origin/main -- 'crates/stella-pipeline/*'
origin/main:.../flip_halt_arming.rs:31:        shell_call_result(witness_command),
origin/main:.../flip_halt_arming.rs:42:        .with_tools(PassingShell)
```

Plus a semantic merge conflict in the same build:

```
error[E0004]: non-exhaustive patterns: `stella_protocol::ModelCallRole::Research` not covered
  --> crates/stella-pipeline/src/management_prompt/tests.rs:64:11
```

`management_system_block` is **deliberately** exhaustive (its doc: "a new role routed through the chokepoint must declare its prefix posture here, not escape the family witness by omission"). #1941 added the match; #1953 later added `ModelCallRole::Research`. Neither PR is wrong alone — the match is doing its job — but nothing made #1953 answer it.

### (2) Clippy fails workspace-wide — the same #1953 argument

```
error: this function has too many arguments (8/7)
    --> crates/stella-pipeline/src/pipeline.rs:1458:5   (plan_stage)
```

#1953 added `research: &[ResearchFinding]` to `plan_stage`, taking it from 7 parameters to 8. `make lint` runs at `-D warnings`, so this is an error.

### (3) rustdoc fails — a link to a private item

```
error: unresolved link to `SkipReason::NoResumePoint`
  --> crates/stella-cli/src/daemon/boot.rs:59
```

`SkipReason` is `pub(super)`, so it is absent from a non-private rustdoc build. This is the *same class* as the bug #1965 ("unbreak main — rustdoc private-link") fixed in `stella-store`; that PR fixed one instance and this one remained.

## How it got past CI

Worth understanding before fixing, because the fix for each symptom is trivial and the fix for the cause is not.

(1)'s `Research` arm and (2) are classic semantic merge conflicts: #1953 and #1941/#1778 were each green against a `main` that lacked the other. That is a merge-queue / re-run-before-merge gap, not an author error.

(1)'s missing fixtures are different and more concerning — #1945's own required check should have caught a test file that does not compile. #1965's description records the same shape for #1952: "auto-merged seconds after its `fmt + clippy + test` job failed on the `cargo doc -D warnings` step (the merge landed at 01:03:40Z; the check concluded red in the same run)". That is **#1645** (`enforce_admins` off, pre-push gate routinely bypassed, auto-merge racing the checks), and these are concrete instances for it.

## Status — all three are fixed on #1964's branch

Fixed there because that PR could not be verified, let alone merged, on a base whose tests do not build. Commits `8923573` and `146e1ec`:

- **Fixtures reconstructed** in `verification_hardening.rs` (the parent module, so the child reaches them via its existing `use super::*`, and `tests.rs` — a god file at its ceiling — does not grow). Semantics pinned by the test passing *for the stated reason*: the command rides under the `command` key `flip_halt::command_of` reads, and the output carries the trailing `[exit code: 0]` marker `flip_halt::exit_status` parses. Without either exact choice `FlipHalt::observe` can never latch and `an_authored_witness_arms_the_revision_flip_halt` would be green while proving nothing.
- **`ModelCallRole::Research`** joins the "never dispatched through the management chokepoint" arm — correct, because research calls are sub-agents run through `Engine::run_sub_agent_with_sender`, not `metered_raw_call`.
- **`plan_stage`** takes the `Spend<'_>` the pipeline already uses for exactly the `budget` + `total` pair, rather than the two loose. That is the established idiom in this crate and removes a line at each of the three call sites — deliberately not an `#[allow(clippy::too_many_arguments)]`.
- **The doc link** is demoted to a code span, matching #1965's fix for the sibling case.

`cargo test -p stella-pipeline`: 588 unit + 22 integration, 0 failures. Workspace clippy and `stella-cli` rustdoc clean.

**This issue exists so unbreaking `main` is tracked independently of whether #1964 merges.** If it stalls, cherry-pick those two commits — they are self-contained, and only the `plan_stage` signature touches non-test code.

## Definition of done

`make gate` is green on `main`. If the fixtures land as reconstructed rather than as #1945's author originally wrote them, a quick confirmation from that author that the witness still asserts what they intended.

## Related

#1645 (the enforcement gap all three are instances of), #1945 (#1793), #1953 (#1778), #1941 (#1855), #1965, #1964.
