### PR TITLE
feat(stella-core,stella-serve): a turn has no step cap by default

### LINKED ISSUE #6237: A turn stops at 200 steps by default, and a count cannot tell real work from wandering
## Problem

Every turn stops at 200 steps. `EngineConfig::default()` sets `max_steps: 200` in `crates/stella-core/src/driver/config.rs`, and the step loop in `crates/stella-core/src/driver/drive.rs` ends the turn there with a `DeliberateStop`.

A count cannot tell real work from wandering. A prompt that asks for a whole feature, or a run that keeps going until its tests pass, can take thousands of steps. The cap ends those runs at the point where the engine is doing its job.

The engine already has bounds that read evidence: loop detection (five rungs in `crates/stella-core/src/loop_detect.rs`), the stall rung, the budget guard, the turn deadline, and the host's halt predicate. The repository's own record (`crates/stella-tools/src/read.rs`, the $7.83 paging sweep) shows the count did not catch the one case people think it is for.

## What to change

- `EngineConfig::max_steps` becomes `Option<usize>` with a default of `None`. A host that means a count still sets one and gets the same `DeliberateStop`.
- `Engine::max_steps()` returns `Option<usize>`; the `stella-engine` crate docs' loop gates only on `Some`.
- `SubAgentSpec::max_steps` becomes `Option<usize>` so a best-of-N candidate in `crates/stella-cli/src/candidate_workspaces.rs` can carry the parent's cap (none). Research children keep `Some(16)`.
- `stella-serve` stops clamping a caller's `max_steps` to 10,000 (`MAX_SERVED_STEPS` in `crates/stella-serve/src/routes.rs`). Zero is still refused.
- Every comment and doc that says a 200-step cap exists is rewritten. An ADR records the decision.

## Definition of done

- [x] `EngineConfig::default().max_steps` is `None`, and a witness test in `crates/stella-core/src/driver/tests/` runs a turn of more than 200 productive steps to `Completed` under the default config
- [x] A second test pins that a host-set cap still ends the turn with `AbortKind::DeliberateStop` and `step_cap_reason(cap)`
- [x] `stella-serve` honours a requested `max_steps` as asked and still refuses `0`
- [x] No comment, README, or spec still claims a default step cap of 200 (`rg -n "200 step|200-step" crates docs website` finds none about the turn cap)
- [x] An ADR under `docs/adr/` records the decision and is indexed in `docs/adr/README.md` and `docs/manifest.json`
- [x] `make guards-fast` passes and CI is green

---

### Verification note — autonomous PR sweep, 2026-09-06

The last box is ticked on the evidence below, measured on PR #6240's head `bcaca5e`. It was correctly left unticked by three earlier sweeps: until this head's run finished, the CI half was not something anyone could claim.

**CI is green.** All 29 check runs on `bcaca5e` are `success` or `skipped`, with one exception named below. The two that took longest and settle the compiling half:

| check | conclusion | finished |
|---|---|---|
| `fmt + clippy + test` | success | 11:23:42Z |
| `Analyze (rust)` (CodeQL) | success | 11:10:00Z |
| `cargo check on the declared MSRV` | success | 11:01:03Z |
| `the platform split still compiles on Windows` | success | 11:01:52Z |
| `the macOS-only dependency table still compiles` | success | 11:00:13Z |
| `build image + smoke the container` | success | 11:02:59Z |
| `cargo deny + cargo audit` | success | 11:02:33Z |
| `docs/wire still matches the types` | success | 11:00:49Z |

**`make guards-fast` passes**, and the evidence for it is CI's rather than a laptop's. `gate steps no other workflow runs` (success, 10:59:16Z) and `guard self-tests` (success, 11:02:48Z) run the toolchain-free guards, `shellcheck` included. That matters here specifically: the sweep comment on #6240 at 11:01 recorded `guards-fast` green locally *except* `shellcheck`, which was not installed on that machine, and AGENTS.md is explicit that a lint that did not run must not read as a lint that found nothing. The CI job is what closes that gap, so this box does not rest on the local run.

**The one non-green check is `dod / dod` itself** (failure, 10:58:50Z), and it is red on exactly this box — the check that this tick exists to clear. Its own failure message says ticking does not re-run it; `dod-recheck.yml` reacts to this edit and re-runs the failed check on the PR.

Nothing else was ticked in this pass. The five boxes above were already ticked by the author.

### PR DESCRIPTION
**Pull request by macanderson**
## What & why

A turn no longer stops at 200 steps. `EngineConfig::max_steps` is now `Option<usize>` and the default is `None`.

A count cannot tell a turn doing ten thousand steps of real work from one that is wandering, so a default cap ended both. What ends a wandering turn is evidence the count never carries: loop detection reads what each call returned, the stall rung reads how long the turn slept, the budget guard reads what it cost, the turn budget reads how long it ran, and the halt predicate reads whether the goal is met. Each fires on the first evidence of its failure. The repository's own record (`crates/stella-tools/src/read.rs`, the $7.83 paging sweep) shows the cap did not catch the one case people think it is for; a new detector rung did.

The mechanism stays for a host that means a count: a test that must end, a served turn whose caller asks for a bound, a research sub-agent. Each sets `Some(n)` and gets the same `DeliberateStop` with the same reason string.

Also in this PR, because leaving them made the change incoherent:

- `SubAgentSpec::max_steps` is `Option<usize>`, so a best-of-N candidate (`candidate_workspaces.rs`, which copies the session's cap) carries none. Research children keep `Some(16)`.
- `stella-serve` passes a caller's `max_steps` through as asked instead of clamping it to 10,000. The clamp existed to keep a caller from removing "the last bound"; once the default is no bound, it bounded only the caller who asked for one. Zero is still refused.
- ADR 0031 records the decision. Every comment, README, and spec that said a 200-step cap exists is rewritten.

Exemplar for the shape: an `Option` for "no ceiling" rather than a sentinel, the same way `tool_timeout: Option<Duration>` and `turn_budget: Option<Duration>` already spell it in the same struct.

Closes #6237

## The witness

- [x] This PR includes a witness test (fails on `main`, passes here): `driver::tests::unbounded_by_default::a_long_productive_turn_runs_to_completion_under_the_default_config` runs a thousand distinct productive steps under `EngineConfig::default()` and asserts `Completed`. On `main` the field is a `usize` (the test does not compile) and the default aborts at step 200 with the step-cap reason. The sibling `a_host_set_cap_still_ends_the_turn_where_it_says` pins that a host-set cap still ends the turn as a `DeliberateStop` with `step_cap_reason(cap)`.

## The gate

- [x] `cargo fmt --check`
- [x] clippy on the crates with logic changes: `cargo clippy -p stella-core -p stella-serve --all-targets -- -D warnings`, clean
- [x] tests run locally, scoped per SCR-001: `stella-core driver::` (314 passed) and `subagent::` (41), `stella-serve step` (unit + http), `stella-cli resume::tests` (3), `stella-tui model_footer`, `stella-tools subagent` (19), `stella-engine --doc`; the workspace run is this PR's CI
- [x] `make doc-warnings CARGO_SCOPE="-p stella-core"` clean; `make guards-fast` green including `prose`, `doc-links`, `adr-numbering`, `line-citations`
- [x] Docs updated where behavior changed: `EngineConfig::max_steps` doc, `stella-engine` crate docs' loop, `crates/stella-core/README.md`, `crates/stella-serve/README.md`, `docs/spec/engine-embedding.md`, ADR 0031 + `docs/adr/README.md` + `docs/manifest.json`
- [x] CLA signed
- [x] `Closes #6237` appears both above and as a commit trailer

## Nothing left behind

- [x] Filed: #6238 (the CLI has no flag or setting to opt into a step cap now that there is no default), #6239 (decide, with a census, whether research sub-agents keep their 16-step count cap)

## Ground-rule check

- [x] No I/O added to `stella-core`; no new deps
- [x] No new outbound network calls
- [x] No new cross-boundary types; the `agent.turn.started` lifecycle payload is a `serde_json::Value` and now carries `max_steps: null` for a turn with no cap (no wire schema changes)

## Anything reviewers should know?

The tradeoff, stated plainly and in the ADR: a turn with budget mode `Off`, no deadline, no halt predicate, and a model that keeps producing new but useless calls now runs until a person stops it. Anyone running with no human watching should set a budget or a deadline, which measure the thing they care about. A new stuck shape gets a new detector rung, never a count.

One test is deleted on purpose: `step_cap_is_clamped_to_the_ceiling` in `crates/stella-serve/src/routes.rs` pinned the 10,000 clamp this PR removes, and `a_requested_step_cap_is_honoured_as_asked` replaces it with the opposite claim.

`driver/tests.rs` is a god file at its ceiling; this PR removes five lines from it (the test override that existed only to fight the old cap) and adds one (`mod unbounded_by_default;`), so it ends four lines under.

## Summary by Sourcery

Remove the default step cap from turns while preserving explicit host-configured limits and documenting the resulting execution model.

New Features:
- Allow turns to run without a step limit by default while retaining optional host-configured step caps.
- Represent engine and sub-agent step limits as optional values and propagate them through candidate, research, served, resumed, and lifecycle turn flows.

Bug Fixes:
- Prevent productive turns from being terminated by the previous default 200-step limit.
- Ensure served requests honor explicit step caps instead of silently clamping them to 10,000.

Enhancements:
- Document evidence-based turn termination and the updated embedding and serving behavior.
- Preserve deliberate-stop semantics and cap reasons for hosts that explicitly configure a limit.

Documentation:
- Add ADR 0031 and update repository documentation, specifications, READMEs, and lifecycle documentation for the no-cap default.

Tests:
- Add coverage proving long productive turns complete under the default configuration and explicit host caps still terminate turns as requested.
- Update affected tests for optional step-cap configuration and resumed turns.

### CODE REVIEW

**Comment by macanderson** [comment]
**Merge conflict resolved — your ADR is now 0031, not 0030.**

This branch was un-mergeable against `main`. The conflict was in `docs/adr/README.md` and `docs/manifest.json`, and it was not a text clash but an **ADR number collision**: #6204 merged "The Wrapper Socket Is the Plugin SDK" as ADR **0030** while this branch was open under the same number. Both are shared cells every ADR-adding branch writes, and neither author was wrong — the number was free when each branch was cut. `check-adr-numbering` is what would have caught it, and only after the merge.

`main`'s record keeps the number it merged under. This one moved to **0031**:

- `docs/adr/0030-a-turn-has-no-step-cap-by-default.md` → `docs/adr/0031-a-turn-has-no-step-cap-by-default.md`, with its frontmatter `id`, `title` and `#` heading following it.
- `docs/adr/README.md` and `docs/manifest.json` now carry both records, in number order.
- The seven citations that meant *this* record are repointed to "ADR 0031": `stella-cli`'s `agent/resume.rs`, `stella-core`'s README, `driver/config.rs`, `driver/tests/unbounded_by_default.rs`, `stella-engine`'s `lib.rs`, `stella-serve`'s README, and `docs/spec/engine-embedding.md`. Every remaining "ADR 0030" in the tree means the wrapper-socket record and was left alone.

A merge commit rather than a rebase, so anyone holding this branch keeps their checkout (AGENTS.md § "Merge conflict").

**Verified on the merged tree**, not asserted: `make guards-fast` green, including `check-adr-numbering` (*31 records, every number unique, every heading and id in agreement, every record indexed*), `check-doc-links` (1265 citations resolve), `check-prose` and `check-line-citations` (none added), and `cargo fmt --check`. No Rust behaviour changed — the diff outside the rename is comment text.

Worth knowing for whoever picks this up: `check-prose` reads the **index**, not the working tree, so with a conflict resolved on disk but left unstaged it counts every merge stage and reports 3× the real number (`11 allowed, 33 found` here). `git add` the resolution before believing that guard.

Two things still outstanding on this PR, neither of them mine to close:

- The fresh CI run this push triggered has to go green — that is also the last unchecked DoD box on #6237 (`make guards-fast` passes and CI is green). `guards-fast` is now demonstrated; CI is not yet.
- Sourcery has posted no review on this PR. Its 250,000-character weekly budget is spent, so it is rate-limited across the whole repo right now and returns a budget notice instead of an assessment. Nothing here is waiting on a `❌` you have not seen — there is no table.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by macanderson** [comment]
**Pushed a conflict resolution and one compile fix to this branch — pull before your next push.**

Automated PR sweep. This branch was `mergeable_state: dirty` against `main` and `fmt + clippy + test` was red. Two commits: `4b46cf6`-equivalent merge (`53f4784..bcaca5e`).

### 1. The conflict: #6232 landed on `main` while this branch was in flight

`main` picked up "Delete the engine builder shims" (#6232), which removed `Engine::with_sleeper` and nine per-seam setters. Three files conflicted, resolved as follows:

- **`crates/stella-core/src/driver.rs`** — took `main`'s deletion of all ten builders. This branch must not resurrect them; it kept only its own rewritten `Engine::max_steps` doc for the `Option` return.
- **`crates/stella-core/src/driver/lifecycle.rs`** — kept both halves of `turn_started_payload`'s doc: this branch's `max_steps: null` paragraph, and `main`'s `lane` paragraph, which now cites `TurnCapabilities` rather than the deleted `with_sleeper`.
- **`crates/stella-core/src/driver/tests.rs`** — declared both new modules, `streaming_deadline` (from #6232's god-file split) and `unbounded_by_default` (this branch's).

### 2. The semantic conflict git had nothing to report about

`crates/stella-core/src/driver/tests/unbounded_by_default.rs` was written against `Engine::with_sleeper` and no longer compiled after the merge — `error[E0599]: no associated function named 'with_sleeper'`. The fixture binds no seams, so it now writes `TurnCapabilities::none()` and calls `Engine::assemble`, the shape `driver/tests/loop_abort.rs` uses. Nothing else in the tree still names a deleted builder (grepped `Engine::with_sleeper` and all nine `engine.with_*(` spellings — zero hits).

### 3. The deleted-test guard was a stale payload, not a real gap

`no test disappears in the merge unacknowledged` failed on the previous head. The only removed test is `step_cap_is_clamped_to_the_ceiling`, and this description already names it — the failing run read the event-payload snapshot from before that sentence was added. Reproduced both directions locally:

```
$ ./scripts/check-deleted-tests.sh origin/main
  step_cap_is_clamped_to_the_ceiling          # (no body available locally)

$ ./scripts/check-deleted-tests.sh --fixture-pr-body '<this description>' origin/main
check-deleted-tests: OK — 1 removed test(s), each named in the PR description or a commit.
```

The push is a fresh `pull_request` event, so the guard reads the live body.

### Evidence, measured on `bcaca5e`

- `cargo check -p stella-core --all-targets` — exit 0
- `cargo test -p stella-core unbounded_by_default` — 2 passed, 0 failed (`a_long_productive_turn_runs_to_completion_under_the_default_config`, `a_host_set_cap_still_ends_the_turn_where_it_says`)
- `cargo fmt --check` — clean
- Toolchain-free guards: `prose`, `line-citations`, `file-size`, `doc-links`, `left-behind`, `lockfile-sync`, `god-files`, `invariants`, `adr-numbering` — all exit 0. `shellcheck` is not installed on this machine and did not run; this diff touches no shell script.

The compiling half of the workspace is CI's, per CLAUDE.md.

**Still open and not mine to close:** `dod / dod` is red because #6237's last box — `make guards-fast` passes and CI is green — is unticked. `guards-fast` is green apart from the missing `shellcheck` binary noted above; the CI half needs this head's run to finish first.

---
_Generated by [Claude Code](https://claude.ai/code)_
