### ISSUE TITLE
MSRV gate fails on every PR: libsqlite3-sys 0.38.x uses unstable cfg_select!, unbuildable on the declared 1.90

### ISSUE THREAD

**Issue by macanderson** [macanderson/stella#1105]
## Summary

The `msrv` workflow (`cargo +1.90 check --workspace --locked`) fails on **every open PR** and has since it was added in #1088. It is not caused by any one branch — I confirmed identical failures on `fix/verification-instrumentation`, `worktree-issue-batch-p2`, `fix/911-panic-safe-env-restore`, `worktree-tool-foundry-authorship`, and both of the CI-repair PRs (#1101, #1103).

It does **not** show up as red on pushes to `main`, because the workflow triggers only on `pull_request` and a weekly `schedule`. So main's own runs look clean once #1101 and #1103 land, while every PR still carries one red check.

## The failure

```
error[E0658]: use of unstable library feature `cfg_select`
  --> /home/runner/.cargo/registry/src/.../libsqlite3-sys-0.38.1/build.rs:110:9
   |
110|         cfg_select! {
   |         ^^^^^^^^^^
   = note: see issue #115585
error: could not compile `libsqlite3-sys` (build script) due to 1 previous error
```

## What I verified

- `libsqlite3-sys` **0.38.1 and 0.38.0** both use `cfg_select!` in `build.rs` (2 sites). **0.37.0 does not.** We are pinned to 0.38.1 via `rusqlite 0.40.1`.
- The pin predates the CI-repair work — `Cargo.lock` already carried 0.38.1 before #1097, and #1097's merge commit did not touch that entry. Nothing recent moved it.
- **`cfg_select!` is unstable on every stable toolchain I tested — 1.90, 1.91, 1.93, 1.95, and 1.97** (1.97 is this repo's own `rust-toolchain.toml` pin). So **raising `rust-version` does not fix this**; there is no stable release to raise it to.
- Curiously, `rustup run 1.90 cargo check --workspace --locked` **passes on macOS** against the identical registry source, with `libsqlite3-sys v0.38.1` genuinely recompiled (verified after `cargo clean -p`). The failure is Linux-CI-specific, which points at a feature-resolution difference (the `cfg_select!` sites sit inside `mod build_bundled`, gated on the `bundled` feature we enable) rather than the toolchain version alone. I did not get to the bottom of that difference.
- The normal `ci` job compiles the workspace fine on the stable toolchain — `cargo fmt --check`, `cargo clippy -D warnings`, and `cargo test` all pass on Linux. Only the old-cargo MSRV path trips.

## Why this needs a decision

The gate was introduced (correctly) to test a claim that had never been exercised, and it immediately found the claim is false: `rust-version = "1.90"` is not something this dependency graph can satisfy. The options each carry a real cost, and none is obviously right:

1. **Downgrade the SQLite stack** to `libsqlite3-sys` 0.37.x. `rusqlite 0.40` wants 0.38, so this likely means downgrading `rusqlite` too — a database dependency, not a trivial pin.
2. **Correct the declared MSRV.** Blocked as stated: no stable Rust has `cfg_select!`, so there is no number that makes the claim true while keeping 0.38.x.
3. **Narrow or drop the gate** (e.g. exclude build scripts of third-party crates, or check a subset), accepting that the MSRV claim is aspirational for the bundled-SQLite path.
4. **Wait upstream.** Arguably a bug in `libsqlite3-sys` — a published crate whose build script uses an unstable `std` macro. Worth an upstream issue either way.

I did not want to pick unilaterally, since options 1 and 2 both change the project's public compatibility story.

## Meta

Worth considering separately: this gate landed already-red rather than regressing later, which is why no single commit looks like the culprit. A new CI gate that cannot pass on the commit introducing it might be better landed as non-blocking until it is green, so it does not sit red across every PR.

Found while repairing the two breaks in main's CI (#1101 bench packaging, #1103 shellcheck).
