### ISSUE TITLE
main is red: the sign() doctest asserts a single line break, sign() writes a horizontal-rule footer

### ISSUE THREAD

**Issue by macanderson** [macanderson/stella#4067]
`main` is red on `fmt + clippy + test`. The `sign()` doctest asserts a contract `sign()` does not implement.

```
test crates/stella-autonomy/src/attribution.rs - attribution::sign (line 134) ... FAILED
```

Failing run: https://github.com/macanderson/stella/actions/runs/32319947770

## The mismatch

`crates/stella-autonomy/src/attribution.rs` asserts:

```rust
assert_eq!(sign("body", "Created by stella."), "body\nCreated by stella.");
```

`sign` writes `body\n\n---\nCreated by stella.` — `SEPARATOR` is `"\n\n---\n"`.

## Why two green branches produced a red main

Neither branch was wrong.

- The doctest arrived in #4014 (autonomous, closing #4006), written against the doc comment's prose, which still said *"the join is exactly one line break"*.
- The change to a horizontal-rule footer landed separately. It updated `SEPARATOR` and the summary line, but there was no doctest to update at the time.

Each was green on its own merge commit. `strict: false` branch protection means a pull request need not be up to date with `main` before merging, so neither ever saw the other. The **shared cell is `sign()`'s contract**, not a file both branches edited — which is why git reported no conflict.

This is the same shape AGENTS.md documents for `Cargo.lock` and `scripts/file-size-baseline.txt`, and the reason `main-canary.yml` exists: no pre-merge run can catch it, because neither author's tree is wrong.

## Fix

Correct the doctest to the footer `sign` actually writes, and correct the prose above it in the same change — the prose is what the doctest was written from, and left stale it seeds the next one.

## Verify

```
cargo test -p stella-autonomy --doc
```

Fails on `main`, passes with the fix.

## Worth considering separately

A doc comment whose prose and whose doctest can disagree is the hazard here. `sign()`'s summary line now states the shape (`<body>\n\n---\n<signature>`) directly above an example that demonstrates it, so the two are adjacent and a reader checks them together. Whether that is enough, or whether the separator should be asserted from the constant rather than spelled twice, is a judgement worth making deliberately rather than inheriting from this fix.

---
created by stella*
