### ISSUE TITLE
main is red: #1695 / #1699 / #1680 landed against each other — SidecarApprovalGate, ConsoleGuard and fleet_claims no longer compile

### ISSUE THREAD

**Issue by macanderson** [macanderson/stella#1712]
## Status

`main` does not compile. `cargo check --workspace` and the required
`fmt + clippy + test` job fail at HEAD (`852f7245`) and have failed for the
three commits before it — `5901bf66`, `a1d9c392`, `366472e0`.

Run: https://github.com/macanderson/stella/actions/runs/31067203643 (job
`fmt + clippy + test`).

Every open PR is red for this and nothing else, whatever its own diff says.

## What broke

Three PRs that each passed on their own base landed against each other. None
of the errors is a merge *conflict* — git merged cleanly and the result does
not type-check, which is the failure mode `main` has hit repeatedly (see #1645).

**A. `SidecarApprovalGate` lost the API its callers still use** —
`crates/stella-cli/src/daemon/approval.rs`

```
error[E0609]: no field `wait` on type `&daemon::approval::SidecarApprovalGate`
  --> crates/stella-cli/src/daemon/approval.rs:209, :220
     note: available fields are: `sidecar`, `registry`, `id`, `interrupted`, `deadline`
error[E0599]: no method named `with_wait` found for struct `SidecarApprovalGate`
  --> crates/stella-cli/src/daemon/approval.rs:571, :635
error[E0425]: cannot find value `parked_at` in this scope
  --> crates/stella-cli/src/daemon/approval.rs:140
```

`wait` was replaced by `deadline` on one side of the merge; the call sites and
tests on the other side still say `wait` / `with_wait` / `parked_at`. Almost
certainly #1616's approval-wait deadline (PR #1695) meeting #1627's
resume-at-boot (PR #1699).

**B. `ConsoleGuard` lost `drain_shared` and its `streams` field** —
`crates/stella-cli/src/daemon/console.rs`

```
error[E0599]: no associated function named `drain_shared` found for struct `ConsoleGuard`
  --> crates/stella-cli/src/daemon/console.rs:562
  --> crates/stella-cli/src/main.rs:599
  --> crates/stella-cli/src/daemon/console/tests.rs:276, :285, :296, :301
error[E0560]: struct `ConsoleGuard` has no field named `streams`
  --> crates/stella-cli/src/daemon/console.rs (around :59)
```

Same shape: the panic-safe console drain (PR #1695) restructured `ConsoleGuard`
while another branch kept calling the old associated function.

**C. `fleet_claims.rs` type mismatches + a missing `Debug`** —
`crates/stella-cli/src/fleet_claims.rs` (many sites: 176, 241, 252, 260, 316,
330, 337, 344, 352, 357) and `crates/stella-cli/src/cli.rs:442`

```
error[E0308]: mismatched types                     (fleet_claims.rs, several)
error[E0277]: `cli::Command` doesn't implement `std::fmt::Debug`
```

Consistent with #1136's check-and-set dispatch lease (PR #1680) changing a
claim signature that `cli.rs` and `fleet_claims.rs` had not both been updated
for.

## Repro

```
git fetch origin main && git checkout origin/main
cargo check -p stella-cli --all-targets
```

(The whole workspace is not needed — every error is in `stella-cli`.)

## Constraints

- `crates/stella-cli/src/command_deck.rs`, `src/agent.rs`, `src/agent/tests.rs`
  and `src/fleet_cmd.rs` are **god files closed to growth**; do not raise a
  ceiling in `scripts/file-size-baseline.txt` to make the fix fit.
- The fix is reconciliation, not reversion: each of the three PRs shipped a
  wanted behaviour. Pick the surviving API deliberately (e.g. `deadline` over
  `wait`) and update the other side's call sites and tests to it, rather than
  restoring the older shape.
- One unbreak PR, not three — several parallel unbreak PRs is a documented
  failure mode of this repo's batches.

## Definition of done

`cargo check -p stella-cli --all-targets` and
`cargo clippy -p stella-cli --all-targets -- -D warnings` are clean on `main`,
the `fmt + clippy + test` job is green on `main`, and the tests that were
silently disabled by not compiling (`daemon/console/tests.rs`,
`daemon/approval.rs`'s test module) still assert what their PRs intended —
check each restored call site against the PR that introduced it rather than
deleting the assertion to make it build.

Then `gh pr update-branch` the open PRs so they pick the fix up.

Refs #1616, #1627, #1136, #1645. Related PRs: #1695, #1699, #1680.

**Comment by macanderson** [comment]
Second incident on the same root cause: PR #1717 landed a third reconciliation of #1616 on top of #1711's, authored against the pre-#1711 base, and left half of each design behind — 9 errors at `cargo check -p stella-cli --all-targets` on `2fd06550`.

Including a test function spliced out of two (`drain_shared_skips_…`'s head with `a_panic_drains_the_console_pump`'s body), `main.rs:543` calling a hook that was deleted, `engine.rs:244` calling `park_deadline` which no longer exists, and `fleet_claims.rs` carrying a re-added test whose imports `a47e92b3` had removed.

PR #1720 fixes all nine and restores `a_panic_drains_the_console_pump` (deleted twice now). Leaving this open until that lands.

Filed #1722 for the process failure behind both incidents: nothing detects two open PRs claiming the same issue, and `main` does not require a PR to be up to date with its base — every one of these merges was textually clean and semantically broken.

**Comment by macanderson** [comment]
Closing as resolved — verified against `origin/main` during an issue-status sweep.

Every symbol this issue names as broken is reconciled on main today:

**A. `SidecarApprovalGate`** — `crates/stella-cli/src/daemon/approval.rs` now carries
*one* coherent design, not two spellings: the `wait` field (`:85`) **and** the
`with_wait()` builder that sets it (`:118`), with live call sites at `:100`, `:460`,
`:529`, `:593`. The `parked_at` binding error is gone.

**B. `ConsoleGuard`** — `crates/stella-cli/src/daemon/console.rs` has the `streams`
field (`:446`) and an idempotent drain (`:476`). `drain_shared` no longer exists
*and* is no longer called anywhere in `crates/stella-cli/`.

**C. `fleet_claims` / `Command: Debug`** — neither error appears in main's current
compile output.

The fix landed as a four-PR unbreak chain, none of which carried a closing trailer,
which is why this stayed open:

- #1711 — `Unbreak main: #1695 re-implemented #1682's #1616 and merged over it`
- #1717 — `unbreak main — stella-cli does not compile`
- #1720 — `Unbreak main: #1717 left half of each #1616 design behind`
- #1727 — `the deadline witness named a builder that never survived`

Evidence that the tree as a whole recovered: `ci.yml`'s required
`fmt + clippy + test` job — including `cargo test` over the workspace — was **green
on main at `8adcfd437`** (2026-08-06 06:53Z).

### One caveat, deliberately not folded into this issue

`main` is red again *right now*, but for an unrelated cause: #1736 merged from a
stale base, deleting `fleet_verbs` from `cli.rs`'s `use crate::{…}` list and
re-adding a duplicate `Command::Fullauto` match arm in `main.rs`. That break is
already tracked by PR #1747 and by #1748. It shares no symbol with this issue.

Duplicate of #1713, which describes the same collision from the other side; closing
both.
